### ISSUE TITLE
containerdns-kubeapi编译问题

### ISSUE THREAD

**Issue by yanruogu** [tiglabs/containerdns#11]
1、在编译containerdns-kubeapi的时候，抛出一大堆异常，后来经过反复测试，是需要依赖指定的kubernetes版本，通过kubernetes 1.5版本，完成编译后，结果到处都找不到编译完成后的containerdns-kubeapi的二进制包。。。

2、如果找到这个包的话，在最新的kubernetes 1.8版本中监视1.8的service，又是否会兼容？

**Comment by yangwanli2017** [comment]
1、cd $GOPATH/src/github.com/ipdcode/containerdns/containerdns-kubeapi; go build -v  
     编译时候依赖 kubernetes 1.5.x 版本。
2、与 kubernetes 1.6.x 结合使用没有问题，目前在使用中。 1.7及以上没有试过，应该问题不大，新版本接口一般会兼容老版本。

**Comment by yanruogu** [comment]
编译是没有问题的，是下载了kubernetes 1.5的源码来一起完成编译，没有报错，只是编译完成后，没有生成二进制文件，不知道跑哪儿去了。

**Comment by chenshugang** [comment]
到 containerdns/containerdns-kubeapi 下go build 后，会有2进制文件啊。
-rw-r--r--. 1 root root    30185 Nov 10 06:48 api.go
-rwxr-xr-x. 1 root root 45372545 Nov 10 18:54 containerdns-kubeapi
-rw-r--r--. 1 root root    40307 Nov 10 06:48 server.go

**Comment by yanruogu** [comment]
嗯 ，我将go版本更新到1.9之后，已经能正常生成二进制文件。感谢！

**Comment by yanruogu** [comment]
请问下针对containerdns的配置，有更详细的参数说明文档么？
我找到http://www.infoq.com/cn/articles/jd-618-container-dns-practise
但是这个是针对老版本的配置，更名后的新版本配置，就简单罗列了下参数，不太明白其义

**Comment by yanruogu** [comment]
另外，编译完成后的containerdns-kubeapi在执行时抛出如下异常：
[root@DY-Dm-Usa-Ali-210 containerdns-kubeapi]# ./containerdns-kubeapi --help
./containerdns-kubeapi flag redefined: log_dir
panic: ./containerdns-kubeapi flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420086060, 0x22b5680, 0xc4204a9840, 0x1784e4b, 0x7, 0x17aea56, 0x2f)
	/usr/local/go/src/flag/flag.go:793 +0x5e1
flag.(*FlagSet).StringVar(0xc420086060, 0xc4204a9840, 0x1784e4b, 0x7, 0x0, 0x0, 0x17aea56, 0x2f)
	/usr/local/go/src/flag/flag.go:696 +0x8b
flag.(*FlagSet).String(0xc420086060, 0x1784e4b, 0x7, 0x0, 0x0, 0x17aea56, 0x2f, 0x31308bc20af33e87)
	/usr/local/go/src/flag/flag.go:709 +0x8b
flag.String(0x1784e4b, 0x7, 0x0, 0x0, 0x17aea56, 0x2f, 0xc4204ce360)
	/usr/local/go/src/flag/flag.go:716 +0x69
k8s.io/kubernetes/vendor/github.com/golang/glog.init()
	/home/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog_file.go:41 +0x14a
k8s.io/kubernetes/pkg/labels.init()
	<autogenerated>:1 +0x64
k8s.io/kubernetes/pkg/api/unversioned.init()
	<autogenerated>:1 +0x8c
k8s.io/kubernetes/pkg/api.init()
	<autogenerated>:1 +0x7b
main.init()
	<autogenerated>:1 +0xb6

**Comment by chenshugang** [comment]
有可能你k8s文件中也定义了log_dir，下面会合入glide和makefile的支持，这样依赖和编译都好搞了

**Comment by yanruogu** [comment]
k8s是直接通过git clone拉取的官方代码https://github.com/kubernetes/kubernetes，然后通过git checkout -b release-1.5 origin/release-15直接检出的1.5版本，然后mv kubernetes $GOPATH/src/k8s.io/
其间对代码没有任何改动。。。
话说能不能先提供个二进制包供我们测试下，目前我们的方案用到了你们的containerdns，但现在编译出来的问题都很大。
我的邮件地址：yanwei@douyu.tv
感谢！

**Comment by yanruogu** [comment]
好的，通过https://github.com/tigcode/containerdns/pull/12这个，我已经可以直接拿到编译好的二进制包了
