### ISSUE TITLE
kubeapi 启动时 log_dir报错

### ISSUE THREAD

**Issue by deancn** [tiglabs/containerdns#21]
使用默认的配置启动kubeapi有报错。
/dist/containerdns-kubeapi -config-file ./etc/containerdns-api.conf
./dist/containerdns-kubeapi flag redefined: log_dir
panic: ./dist/containerdns-kubeapi flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc4200a0060, 0x1846520, 0xc42048af30, 0x171b570, 0x7, 0x1747a42, 0x2f)
	/usr/local/go/src/flag/flag.go:810 +0x540
flag.(*FlagSet).StringVar(0xc4200a0060, 0xc42048af30, 0x171b570, 0x7, 0x0, 0x0, 0x1747a42, 0x2f)
	/usr/local/go/src/flag/flag.go:713 +0x8b
flag.(*FlagSet).String(0xc4200a0060, 0x171b570, 0x7, 0x0, 0x0, 0x1747a42, 0x2f, 0xc42048af20)
	/usr/local/go/src/flag/flag.go:726 +0x8b
flag.String(0x171b570, 0x7, 0x0, 0x0, 0x1747a42, 0x2f, 0xc4201b9c30)
	/usr/local/go/src/flag/flag.go:733 +0x69

**Comment by chenshugang** [comment]
这个可能是k8s 库中 定义了 log_dir， 你是用makefile 编译的么？正常makefile 编译没问题的
