### ISSUE TITLE
The version of the containerdns's k8sapi is too old

### ISSUE THREAD

**Issue by shaohk** [tiglabs/containerdns#43]
你好：
       目前构建containerdns依赖的api有点老，还有etcd等，etcd的github地址已经变更了，dns的代码里面引的包还是老包，能否可以根据目前的相关库，更新一版代码？
多谢！

**Comment by yangwanli2017** [comment]
非常感谢你的建议，我们的工程师也在抓紧推出新的版本，以支持较新的k8sapi 和 etcd版本。

**Comment by shaohk** [comment]
非常感谢
