### ISSUE TITLE
EAL设置相关问题讨论

### ISSUE THREAD

**Issue by csxiaomiao** [tiglabs/containerdns#54]
KDNS的配置文件kdns.cfg中，EAL相关的内存设置没有说明
memory = 1024,1024
这个配置应该是指在NUMA架构下node0， node1 分别分配
1024个2MB的Hugepage大页内存的意思， 个人推测 ?

mem-channels = 4 这个配置项是什么意思呢？

请开发者说明一下，谢谢！

**Comment by chenshugang** [comment]
memory 对应dpdk启动参数 --socket-mem，mem-channels 对应 -n
