### ISSUE TITLE
kdns服务的启动的相关问题

### ISSUE THREAD

**Issue by csxiaomiao** [tiglabs/containerdns#55]
./kdns启动后 日志文件中提示：
[2019-01-28 10:48:36.879] [25441] [error] : now just one port supported

经查看源码, netdev,c源程序中：
   
        /* Get number of ports found in scan */
    nb_sys_ports = rte_eth_dev_count();
    if (nb_sys_ports == 0){
        log_msg(LOG_ERR, "No supported Ethernet device found\n");
        exit(-1);
    }
    
    if (nb_sys_ports != 1){
        log_msg(LOG_ERR, "now just one port supported\n");
        exit(-1);
    }

进入DPDK的usertools目录，运行dpdk-setup.sh查看 DPDK Driver与网口的bind绑定配置情况：
Option: 23

Network devices using DPDK-compatible driver
============================================
0000:06:00.1 'I350 Gigabit Network Connection 1521' drv=igb_uio unused=igb
0000:06:00.2 'I350 Gigabit Network Connection 1521' drv=igb_uio unused=igb

Network devices using kernel driver
===================================
0000:06:00.0 'I350 Gigabit Network Connection 1521' if=eno1 drv=igb unused=igb_uio *Active*
0000:06:00.3 'I350 Gigabit Network Connection 1521' if=eno4 drv=igb unused=igb_uio 

No 'Crypto' devices detected
============================

No 'Eventdev' devices detected
==============================

No 'Mempool' devices detected
=============================

No 'Compress' devices detected
==============================

是不是只需要绑定一个网络接口才能正常启动kdns服务？

**Comment by csxiaomiao** [comment]
修改网卡接口DPDK driver bind的设置，只Bind一个interface后，启动提示如下错误：

[root@DPDK bin]# ./kdns
EAL: Detected 24 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:06:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:06:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:06:00.2 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:06:00.3 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
KNI: pci: 06:00:01       8086:1521
ioctl SIOCSIFHWADDR: Timer expired

查看日志 # talk -f /var/log/kdns/kdns.log
[2019-01-28 14:34:06.900] [27432] [info] : Initialising port 0 ...
[2019-01-28 14:34:09.964] [27432] [error] : Fail to set mac 40:F2:E9:F0:A7:FB for kdns: Timer expired

其中mac 40:F2:E9:F0:A7:FB 是已经bind  DPDK driver的网卡接口的MAC地址啊， 跟踪了一下代码

int linux_set_if_mac(const char *ifname, const unsigned char mac[ETH_ALEN])
{
    int fd;
    struct ifreq ifr;

    if (!ifname || strlen(ifname) >= IFNAMSIZ || !mac) {
        return -1;
    }

    fd = socket(PF_INET, SOCK_DGRAM, 0);
    if (fd < 0) {
        perror("socket");
        return -1;
    }

    memset(&ifr, 0, sizeof(ifr));
    snprintf(ifr.ifr_name, sizeof(ifr.ifr_name), "%s", ifname);
    ifr.ifr_hwaddr.sa_family = 1;
    memcpy(ifr.ifr_hwaddr.sa_data, mac, ETH_ALEN);
    if (ioctl(fd, SIOCSIFHWADDR, &ifr)) {
        perror("ioctl SIOCSIFHWADDR");
        close(fd);
        return -1;
    }

    close(fd);
    return 0;
}

好像是上面的ioctl(fd, SIOCSIFHWADDR, &ifr） 出错了，这个问题如何做Troubleshooting呢？

**Comment by chenshugang** [comment]
是的，现在只支持一个网口
