### ISSUE TITLE
README文档中的一处错误

### ISSUE THREAD

**Issue by csxiaomiao** [tiglabs/containerdns#56]
[root@DPDK bin]# ./dpdk-devbind.py --bind=igb_uio kdns
Unknown device: kdns. Please specify device in "bus:slot.func" format
[root@DPDK bin]# ./dpdk-devbind.py --bind=igb_uio 06:00.1
0000:06:00.1 already bound to driver igb_uio, skipping

[root@DPDK bin]# ./dpdk-devbind.py --bind=igb_uio 06:00.2
[root@DPDK bin]# 

dpdk-devbind.py --bind=igb_uio 06:00.1 的格式才正确，最后一个参数是PCIE网卡的bus:slot.func

**Comment by chenshugang** [comment]
Examples:
---------

To display current device status:
        dpdk-devbind.py --status

To bind eth1 from the current driver and move to use igb_uio
        dpdk-devbind.py --bind=igb_uio eth1

To unbind 0000:01:00.0 from using any driver
        dpdk-devbind.py -u 0000:01:00.0

To bind 0000:02:00.0 and 0000:02:00.1 to the ixgbe kernel driver
        dpdk-devbind.py -b ixgbe 02:00.0 02:00.1
里面的脚本因该是可以的，当然这个网卡要存在的条件下。当然你的方式也是可以的
