### ISSUE TITLE
KDNS 配置中kni-vip地址是什么意思

### ISSUE THREAD

**Issue by csxiaomiao** [tiglabs/containerdns#57]
; BGP 发布的VIP
kni-vip = 10.17.9.100

项目README中给出的kni-vip地址是什么意思呢？
没有修改的话，在
  dns_tcp_process_init(g_dns_cfg->netdev.kni_vip);
调用处出错，提示：

KNI: pci: 04:00:00       8086:10c9
.........................done
Starting core 3 conf:  rx=0, tx=1 
Starting core 5 conf:  rx=1, tx=2 
Starting core 7 conf:  rx=2, tx=3 
bind: Cannot assign requested address

请教一下...

**Comment by chenshugang** [comment]
这个就是对外服务的VIP地址，绑定端口式启动时候支持tcp而绑定的。这个是物理机可见的地址，不行的话你可以绑定0.0.0.0

**Comment by chenshugang** [comment]
使用的问题，可以加我weixin: chen_94337035
